// Generated by using torchexport::export() -> do not edit by hand
#include <Rcpp.h>
#include <torch.h>
#include "causalot_types.h"

torch::Tensor rcpp_softmin_torch_cpp_ (double lambda, torch::Tensor cost_, torch::Tensor y_potential_, torch::Tensor b_log_);
