// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "causalOT_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootStrap_
Rcpp::NumericVector bootStrap_(Rcpp::List& w_list, int nboot, Rcpp::Environment& object);
RcppExport SEXP _causalOT_bootStrap_(SEXP w_listSEXP, SEXP nbootSEXP, SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type w_list(w_listSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(bootStrap_(w_list, nboot, object));
    return rcpp_result_gen;
END_RCPP
}
// sbw_oop_bs_
Rcpp::NumericVector sbw_oop_bs_(Rcpp::List& w_list, int nboot, matrix& source, vector& target, Rcpp::NumericVector& a);
RcppExport SEXP _causalOT_sbw_oop_bs_(SEXP w_listSEXP, SEXP nbootSEXP, SEXP sourceSEXP, SEXP targetSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type w_list(w_listSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< matrix& >::type source(sourceSEXP);
    Rcpp::traits::input_parameter< vector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sbw_oop_bs_(w_list, nboot, source, target, a));
    return rcpp_result_gen;
END_RCPP
}
// entBW_obj_
double entBW_obj_(const SEXP& vars_, const SEXP& A_, double delta);
RcppExport SEXP _causalOT_entBW_obj_(SEXP vars_SEXP, SEXP A_SEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type vars_(vars_SEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(entBW_obj_(vars_, A_, delta));
    return rcpp_result_gen;
END_RCPP
}
// entBW_grad_
vector entBW_grad_(const SEXP& vars_, const SEXP& A_, double delta);
RcppExport SEXP _causalOT_entBW_grad_(SEXP vars_SEXP, SEXP A_SEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type vars_(vars_SEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(entBW_grad_(vars_, A_, delta));
    return rcpp_result_gen;
END_RCPP
}
// logSumExp
double logSumExp(vector& x_);
RcppExport SEXP _causalOT_logSumExp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vector& >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(logSumExp(x_));
    return rcpp_result_gen;
END_RCPP
}
// rowLogSumExp
vector rowLogSumExp(matrix& x_);
RcppExport SEXP _causalOT_rowLogSumExp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< matrix& >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(rowLogSumExp(x_));
    return rcpp_result_gen;
END_RCPP
}
// colLogSumExp
vector colLogSumExp(matrix& x_);
RcppExport SEXP _causalOT_colLogSumExp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< matrix& >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(colLogSumExp(x_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_causalOT_bootStrap_", (DL_FUNC) &_causalOT_bootStrap_, 3},
    {"_causalOT_sbw_oop_bs_", (DL_FUNC) &_causalOT_sbw_oop_bs_, 5},
    {"_causalOT_entBW_obj_", (DL_FUNC) &_causalOT_entBW_obj_, 3},
    {"_causalOT_entBW_grad_", (DL_FUNC) &_causalOT_entBW_grad_, 3},
    {"_causalOT_logSumExp", (DL_FUNC) &_causalOT_logSumExp, 1},
    {"_causalOT_rowLogSumExp", (DL_FUNC) &_causalOT_rowLogSumExp, 1},
    {"_causalOT_colLogSumExp", (DL_FUNC) &_causalOT_colLogSumExp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_causalOT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
