// Generated by rstantools.  Do not edit by hand.

/*
    causalOT is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    causalOT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with causalOT.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_gp_hyper_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_gp_hyper");
    reader.add_event(145, 143, "end", "model_gp_hyper");
    return reader;
}
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type, Eigen::Dynamic, Eigen::Dynamic>
pol_kern(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
             const T1__& theta,
             const T2__& gamma,
             const T3__& sigma,
             const T4__& p, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 9;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(cost));
        current_statement_begin__ = 11;
        validate_non_negative_index("K", "N", N);
        validate_non_negative_index("K", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> K(N, N);
        stan::math::initialize(K, DUMMY_VAR__);
        stan::math::fill(K, DUMMY_VAR__);
        current_statement_begin__ = 13;
        for (int j = 1; j <= N; ++j) {
            current_statement_begin__ = 14;
            for (int i = j; i <= N; ++i) {
                current_statement_begin__ = 15;
                stan::model::assign(K, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                            ((gamma * gamma) * pow((1.0 + ((theta * theta) * get_base1(cost, i, j, "cost", 1))), p)), 
                            "assigning variable K");
                current_statement_begin__ = 16;
                stan::model::assign(K, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            get_base1(K, i, j, "K", 1), 
                            "assigning variable K");
            }
        }
        current_statement_begin__ = 19;
        for (int i = 1; i <= N; ++i) {
            current_statement_begin__ = 20;
            stan::model::assign(K, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        (stan::model::rvalue(K, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), "K") + (sigma * sigma)), 
                        "assigning variable K");
        }
        current_statement_begin__ = 22;
        return stan::math::promote_scalar<fun_return_scalar_t__>(K);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct pol_kern_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
             const T1__& theta,
             const T2__& gamma,
             const T3__& sigma,
             const T4__& p, std::ostream* pstream__) const {
        return pol_kern(cost, theta, gamma, sigma, p, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type, Eigen::Dynamic, Eigen::Dynamic>
rbf_kern(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
             const T1__& theta,
             const T2__& gamma,
             const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 31;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(cost));
        current_statement_begin__ = 33;
        validate_non_negative_index("K", "N", N);
        validate_non_negative_index("K", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> K(N, N);
        stan::math::initialize(K, DUMMY_VAR__);
        stan::math::fill(K, DUMMY_VAR__);
        current_statement_begin__ = 35;
        for (int j = 1; j <= (N - 1); ++j) {
            current_statement_begin__ = 36;
            for (int i = (j + 1); i <= N; ++i) {
                {
                current_statement_begin__ = 37;
                local_scalar_t__ calc(DUMMY_VAR__);
                (void) calc;  // dummy to suppress unused var warning
                stan::math::initialize(calc, DUMMY_VAR__);
                stan::math::fill(calc, DUMMY_VAR__);
                stan::math::assign(calc,((gamma * gamma) * stan::math::exp((((-(0.5) * 1) / (theta * theta)) * get_base1(cost, i, j, "cost", 1)))));
                current_statement_begin__ = 38;
                stan::model::assign(K, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                            calc, 
                            "assigning variable K");
                current_statement_begin__ = 39;
                stan::model::assign(K, 
                            stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            calc, 
                            "assigning variable K");
                }
            }
        }
        current_statement_begin__ = 42;
        for (int i = 1; i <= N; ++i) {
            current_statement_begin__ = 43;
            stan::model::assign(K, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        ((gamma * gamma) + (sigma * sigma)), 
                        "assigning variable K");
        }
        current_statement_begin__ = 46;
        return stan::math::promote_scalar<fun_return_scalar_t__>(K);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct rbf_kern_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
             const T1__& theta,
             const T2__& gamma,
             const T3__& sigma, std::ostream* pstream__) const {
        return rbf_kern(cost, theta, gamma, sigma, pstream__);
    }
};
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, Eigen::Dynamic>
linear_kern(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
                const T1__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 56;
        int N(0);
        (void) N;  // dummy to suppress unused var warning
        stan::math::fill(N, std::numeric_limits<int>::min());
        stan::math::assign(N,rows(cost));
        current_statement_begin__ = 58;
        validate_non_negative_index("K", "N", N);
        validate_non_negative_index("K", "N", N);
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> K(N, N);
        stan::math::initialize(K, DUMMY_VAR__);
        stan::math::fill(K, DUMMY_VAR__);
        stan::math::assign(K,cost);
        current_statement_begin__ = 60;
        for (int i = 1; i <= N; ++i) {
            current_statement_begin__ = 61;
            stan::model::assign(K, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                        (stan::model::rvalue(K, stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), "K") + (sigma * sigma)), 
                        "assigning variable K");
        }
        current_statement_begin__ = 64;
        return stan::math::promote_scalar<fun_return_scalar_t__>(K);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct linear_kern_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, Eigen::Dynamic>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, Eigen::Dynamic>& cost,
                const T1__& sigma, std::ostream* pstream__) const {
        return linear_kern(cost, sigma, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_gp_hyper
  : public stan::model::model_base_crtp<model_gp_hyper> {
private:
        int N;
        vector_d y;
        matrix_d discrep;
        double p;
        int kernel;
        double a;
        double b;
        vector_d mu;
        int num_param;
        double delta_x;
        int use_gamma;
public:
    model_gp_hyper(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_gp_hyper(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_gp_hyper_namespace::model_gp_hyper";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 69;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);
            current_statement_begin__ = 70;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(N));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 71;
            validate_non_negative_index("discrep", "N", N);
            validate_non_negative_index("discrep", "N", N);
            context__.validate_dims("data initialization", "discrep", "matrix_d", context__.to_vec(N,N));
            discrep = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, N);
            vals_r__ = context__.vals_r("discrep");
            pos__ = 0;
            size_t discrep_j_2_max__ = N;
            size_t discrep_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < discrep_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < discrep_j_1_max__; ++j_1__) {
                    discrep(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 72;
            context__.validate_dims("data initialization", "p", "double", context__.to_vec());
            p = double(0);
            vals_r__ = context__.vals_r("p");
            pos__ = 0;
            p = vals_r__[pos__++];
            current_statement_begin__ = 73;
            context__.validate_dims("data initialization", "kernel", "int", context__.to_vec());
            kernel = int(0);
            vals_i__ = context__.vals_i("kernel");
            pos__ = 0;
            kernel = vals_i__[pos__++];
            check_greater_or_equal(function__, "kernel", kernel, 1);
            check_less_or_equal(function__, "kernel", kernel, 3);
            current_statement_begin__ = 74;
            context__.validate_dims("data initialization", "a", "double", context__.to_vec());
            a = double(0);
            vals_r__ = context__.vals_r("a");
            pos__ = 0;
            a = vals_r__[pos__++];
            current_statement_begin__ = 75;
            context__.validate_dims("data initialization", "b", "double", context__.to_vec());
            b = double(0);
            vals_r__ = context__.vals_r("b");
            pos__ = 0;
            b = vals_r__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 79;
            validate_non_negative_index("mu", "N", N);
            mu = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            stan::math::fill(mu, DUMMY_VAR__);
            stan::math::assign(mu,rep_vector(0.0, N));
            current_statement_begin__ = 80;
            num_param = int(0);
            stan::math::fill(num_param, std::numeric_limits<int>::min());
            stan::math::assign(num_param,1);
            current_statement_begin__ = 81;
            delta_x = double(0);
            stan::math::fill(delta_x, DUMMY_VAR__);
            stan::math::assign(delta_x,stan::math::sqrt(max(discrep)));
            current_statement_begin__ = 82;
            use_gamma = int(0);
            stan::math::fill(use_gamma, std::numeric_limits<int>::min());
            stan::math::assign(use_gamma,0);
            // execute transformed data statements
            current_statement_begin__ = 83;
            if (as_bool(logical_eq(kernel, 3))) {
                current_statement_begin__ = 83;
                stan::math::assign(num_param, 0);
            }
            current_statement_begin__ = 85;
            if (as_bool(logical_neq(a, 0.0))) {
                current_statement_begin__ = 85;
                stan::math::assign(use_gamma, 1);
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 89;
            num_params_r__ += 1;
            current_statement_begin__ = 90;
            validate_non_negative_index("theta_half", "num_param", num_param);
            num_params_r__ += (1 * num_param);
            current_statement_begin__ = 91;
            validate_non_negative_index("gamma_half", "num_param", num_param);
            num_params_r__ += (1 * num_param);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_gp_hyper() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 89;
        if (!(context__.contains_r("sigma_half")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_half missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_half");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma_half", "double", context__.to_vec());
        double sigma_half(0);
        sigma_half = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0.0, sigma_half);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_half: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 90;
        if (!(context__.contains_r("theta_half")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_half missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_half");
        pos__ = 0U;
        validate_non_negative_index("theta_half", "num_param", num_param);
        context__.validate_dims("parameter initialization", "theta_half", "double", context__.to_vec(num_param));
        std::vector<double> theta_half(num_param, double(0));
        size_t theta_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < theta_half_k_0_max__; ++k_0__) {
            theta_half[k_0__] = vals_r__[pos__++];
        }
        size_t theta_half_i_0_max__ = num_param;
        for (size_t i_0__ = 0; i_0__ < theta_half_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0.0, theta_half[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_half: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 91;
        if (!(context__.contains_r("gamma_half")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable gamma_half missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("gamma_half");
        pos__ = 0U;
        validate_non_negative_index("gamma_half", "num_param", num_param);
        context__.validate_dims("parameter initialization", "gamma_half", "double", context__.to_vec(num_param));
        std::vector<double> gamma_half(num_param, double(0));
        size_t gamma_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < gamma_half_k_0_max__; ++k_0__) {
            gamma_half[k_0__] = vals_r__[pos__++];
        }
        size_t gamma_half_i_0_max__ = num_param;
        for (size_t i_0__ = 0; i_0__ < gamma_half_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0.0, gamma_half[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable gamma_half: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 89;
            local_scalar_t__ sigma_half;
            (void) sigma_half;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_half = in__.scalar_lb_constrain(0.0, lp__);
            else
                sigma_half = in__.scalar_lb_constrain(0.0);
            current_statement_begin__ = 90;
            std::vector<local_scalar_t__> theta_half;
            size_t theta_half_d_0_max__ = num_param;
            theta_half.reserve(theta_half_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < theta_half_d_0_max__; ++d_0__) {
                if (jacobian__)
                    theta_half.push_back(in__.scalar_lb_constrain(0.0, lp__));
                else
                    theta_half.push_back(in__.scalar_lb_constrain(0.0));
            }
            current_statement_begin__ = 91;
            std::vector<local_scalar_t__> gamma_half;
            size_t gamma_half_d_0_max__ = num_param;
            gamma_half.reserve(gamma_half_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < gamma_half_d_0_max__; ++d_0__) {
                if (jacobian__)
                    gamma_half.push_back(in__.scalar_lb_constrain(0.0, lp__));
                else
                    gamma_half.push_back(in__.scalar_lb_constrain(0.0));
            }
            // transformed parameters
            current_statement_begin__ = 95;
            validate_non_negative_index("L", "N", N);
            validate_non_negative_index("L", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> L(N, N);
            stan::math::initialize(L, DUMMY_VAR__);
            stan::math::fill(L, DUMMY_VAR__);
            // transformed parameters block statements
            {
            current_statement_begin__ = 97;
            validate_non_negative_index("Sigma", "N", N);
            validate_non_negative_index("Sigma", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Sigma(N, N);
            stan::math::initialize(Sigma, DUMMY_VAR__);
            stan::math::fill(Sigma, DUMMY_VAR__);
            current_statement_begin__ = 99;
            if (as_bool(logical_eq(kernel, 1))) {
                current_statement_begin__ = 100;
                stan::math::assign(Sigma, pol_kern(discrep, get_base1(theta_half, 1, "theta_half", 1), get_base1(gamma_half, 1, "gamma_half", 1), sigma_half, p, pstream__));
            } else if (as_bool(logical_eq(kernel, 2))) {
                current_statement_begin__ = 106;
                stan::math::assign(Sigma, rbf_kern(discrep, get_base1(theta_half, 1, "theta_half", 1), get_base1(gamma_half, 1, "gamma_half", 1), sigma_half, pstream__));
            } else if (as_bool(logical_eq(kernel, 3))) {
                current_statement_begin__ = 111;
                stan::math::assign(Sigma, linear_kern(discrep, sigma_half, pstream__));
            }
            current_statement_begin__ = 113;
            stan::math::assign(L, cholesky_decompose(Sigma));
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 95;
            size_t L_j_1_max__ = N;
            size_t L_j_2_max__ = N;
            for (size_t j_1__ = 0; j_1__ < L_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < L_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(L(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: L" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable L: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            current_statement_begin__ = 122;
            lp_accum__.add(normal_log<propto__>(sigma_half, 0.0, 0.5));
            current_statement_begin__ = 124;
            if (as_bool(logical_eq(kernel, 2))) {
                current_statement_begin__ = 125;
                if (as_bool(logical_eq(use_gamma, 0))) {
                    current_statement_begin__ = 126;
                    lp_accum__.add(normal_log<propto__>(get_base1(theta_half, 1, "theta_half", 1), 0.0, (delta_x / 3.0)));
                } else if (as_bool(logical_eq(use_gamma, 1))) {
                    current_statement_begin__ = 128;
                    lp_accum__.add(inv_gamma_log<propto__>(get_base1(theta_half, 1, "theta_half", 1), a, b));
                }
                current_statement_begin__ = 130;
                lp_accum__.add(normal_log<propto__>(get_base1(gamma_half, 1, "gamma_half", 1), 0.0, 2.5));
            }
            current_statement_begin__ = 134;
            lp_accum__.add(multi_normal_cholesky_log<propto__>(y, mu, L));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("sigma_half");
        names__.push_back("theta_half");
        names__.push_back("gamma_half");
        names__.push_back("L");
        names__.push_back("marg_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(num_param);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(num_param);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_gp_hyper_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double sigma_half = in__.scalar_lb_constrain(0.0);
        vars__.push_back(sigma_half);
        std::vector<double> theta_half;
        size_t theta_half_d_0_max__ = num_param;
        theta_half.reserve(theta_half_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < theta_half_d_0_max__; ++d_0__) {
            theta_half.push_back(in__.scalar_lb_constrain(0.0));
        }
        size_t theta_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < theta_half_k_0_max__; ++k_0__) {
            vars__.push_back(theta_half[k_0__]);
        }
        std::vector<double> gamma_half;
        size_t gamma_half_d_0_max__ = num_param;
        gamma_half.reserve(gamma_half_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < gamma_half_d_0_max__; ++d_0__) {
            gamma_half.push_back(in__.scalar_lb_constrain(0.0));
        }
        size_t gamma_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < gamma_half_k_0_max__; ++k_0__) {
            vars__.push_back(gamma_half[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 95;
            validate_non_negative_index("L", "N", N);
            validate_non_negative_index("L", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> L(N, N);
            stan::math::initialize(L, DUMMY_VAR__);
            stan::math::fill(L, DUMMY_VAR__);
            // do transformed parameters statements
            {
            current_statement_begin__ = 97;
            validate_non_negative_index("Sigma", "N", N);
            validate_non_negative_index("Sigma", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> Sigma(N, N);
            stan::math::initialize(Sigma, DUMMY_VAR__);
            stan::math::fill(Sigma, DUMMY_VAR__);
            current_statement_begin__ = 99;
            if (as_bool(logical_eq(kernel, 1))) {
                current_statement_begin__ = 100;
                stan::math::assign(Sigma, pol_kern(discrep, get_base1(theta_half, 1, "theta_half", 1), get_base1(gamma_half, 1, "gamma_half", 1), sigma_half, p, pstream__));
            } else if (as_bool(logical_eq(kernel, 2))) {
                current_statement_begin__ = 106;
                stan::math::assign(Sigma, rbf_kern(discrep, get_base1(theta_half, 1, "theta_half", 1), get_base1(gamma_half, 1, "gamma_half", 1), sigma_half, pstream__));
            } else if (as_bool(logical_eq(kernel, 3))) {
                current_statement_begin__ = 111;
                stan::math::assign(Sigma, linear_kern(discrep, sigma_half, pstream__));
            }
            current_statement_begin__ = 113;
            stan::math::assign(L, cholesky_decompose(Sigma));
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t L_j_2_max__ = N;
                size_t L_j_1_max__ = N;
                for (size_t j_2__ = 0; j_2__ < L_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < L_j_1_max__; ++j_1__) {
                        vars__.push_back(L(j_1__, j_2__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 140;
            double marg_lik;
            (void) marg_lik;  // dummy to suppress unused var warning
            stan::math::initialize(marg_lik, DUMMY_VAR__);
            stan::math::fill(marg_lik, DUMMY_VAR__);
            stan::math::assign(marg_lik,multi_normal_cholesky_log(y, mu, L));
            // validate, write generated quantities
            current_statement_begin__ = 140;
            vars__.push_back(marg_lik);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_gp_hyper";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_half";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < theta_half_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_half" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < gamma_half_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma_half" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t L_j_2_max__ = N;
            size_t L_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < L_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < L_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "L" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "marg_lik";
        param_names__.push_back(param_name_stream__.str());
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_half";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < theta_half_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_half" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t gamma_half_k_0_max__ = num_param;
        for (size_t k_0__ = 0; k_0__ < gamma_half_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "gamma_half" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t L_j_2_max__ = N;
            size_t L_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < L_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < L_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "L" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "marg_lik";
        param_names__.push_back(param_name_stream__.str());
    }
}; // model
}  // namespace
typedef model_gp_hyper_namespace::model_gp_hyper stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
