# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cost_calculation_ <- function(A_, B_, p) {
    .Call(`_causalOT_cost_calculation_`, A_, B_, p)
}

cost_mahal_ <- function(A_, B_, p, estimand) {
    .Call(`_causalOT_cost_mahal_`, A_, B_, p, estimand)
}

kernel_calc_dose_ <- function(X_, z_, p, theta_, gamma_, kernel_, calc_covariance) {
    .Call(`_causalOT_kernel_calc_dose_`, X_, z_, p, theta_, gamma_, kernel_, calc_covariance)
}

similarity_calc_dose_ <- function(X_, z_, calc_covariance) {
    .Call(`_causalOT_similarity_calc_dose_`, X_, z_, calc_covariance)
}

kernel_calc_ <- function(X_, z, p, theta_, gamma_, sigma_2_, kernel_, calc_covariance, estimand) {
    .Call(`_causalOT_kernel_calc_`, X_, z, p, theta_, gamma_, sigma_2_, kernel_, calc_covariance, estimand)
}

kernel_calc_pred_ <- function(X_, X_test_, z, p, theta_, gamma_, sigma_2_, kernel_, calc_covariance, estimand) {
    .Call(`_causalOT_kernel_calc_pred_`, X_, X_test_, z, p, theta_, gamma_, sigma_2_, kernel_, calc_covariance, estimand)
}

kernel_update_ <- function(sim_, z_, p, theta_, gamma_, sigma_2_, kernel_) {
    .Call(`_causalOT_kernel_update_`, sim_, z_, p, theta_, gamma_, sigma_2_, kernel_)
}

similarity_calc_ <- function(X_, z, calc_covariance, estimand) {
    .Call(`_causalOT_similarity_calc_`, X_, z, calc_covariance, estimand)
}

marginal_lik_gp_ <- function(y_, K_) {
    .Call(`_causalOT_marginal_lik_gp_`, y_, K_)
}

kernel_calc_ot_ <- function(X_, z, p, theta_, gamma_, kernel_, calc_covariance, estimand) {
    .Call(`_causalOT_kernel_calc_ot_`, X_, z, p, theta_, gamma_, kernel_, calc_covariance, estimand)
}

cotDualL2_obj_ <- function(vars_, QQ, cost_, pf_, lambda) {
    .Call(`_causalOT_cotDualL2_obj_`, vars_, QQ, cost_, pf_, lambda)
}

cotDualL2_grad_ <- function(vars_, QQ, cost_, pf_, lambda) {
    .Call(`_causalOT_cotDualL2_grad_`, vars_, QQ, cost_, pf_, lambda)
}

cotDual_obj_ <- function(vars_, QQ, cost_, pf_, lambda, penalty) {
    .Call(`_causalOT_cotDual_obj_`, vars_, QQ, cost_, pf_, lambda, penalty)
}

cotDual_grad_ <- function(vars_, QQ, cost_, pf_, lambda, penalty) {
    .Call(`_causalOT_cotDual_grad_`, vars_, QQ, cost_, pf_, lambda, penalty)
}

sbwDual_obj_ <- function(vars_, QQ, pf_, penalty) {
    .Call(`_causalOT_sbwDual_obj_`, vars_, QQ, pf_, penalty)
}

sbwDual_grad_ <- function(vars_, QQ, pf_, penalty) {
    .Call(`_causalOT_sbwDual_grad_`, vars_, QQ, pf_, penalty)
}

otDualL2_obj_ <- function(vars_, a_, b_, cost_, lambda) {
    .Call(`_causalOT_otDualL2_obj_`, vars_, a_, b_, cost_, lambda)
}

otDualL2_grad_ <- function(vars_, a_, b_, cost_, lambda) {
    .Call(`_causalOT_otDualL2_grad_`, vars_, a_, b_, cost_, lambda)
}

otDualL2_obj_self_ <- function(vars_, a_, cost_, lambda) {
    .Call(`_causalOT_otDualL2_obj_self_`, vars_, a_, cost_, lambda)
}

otDualL2_grad_self_ <- function(vars_, a_, cost_, lambda) {
    .Call(`_causalOT_otDualL2_grad_self_`, vars_, a_, cost_, lambda)
}

otL2_grad_ <- function() {
    .Call(`_causalOT_otL2_grad_`)
}

otL2_obj_ <- function() {
    .Call(`_causalOT_otL2_obj_`)
}

otL2_grad_self_ <- function() {
    .Call(`_causalOT_otL2_grad_self_`)
}

otL2_obj_self_ <- function() {
    .Call(`_causalOT_otL2_obj_self_`)
}

